version: "3"

networks:
  pasta_net:
    external: true

services:
  pasta_chat.flask:
    container_name: pasta_chat.flask
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PG_PORT=5432
      - PG_PASS=pasta
      - PG_HOST=pasta_chat.postgres
      - PG_USER=postgres
    networks:
      - pasta_net
    volumes:
      - ./pasta_chat:/pasta_chat
    ports:
      - "8003:80"
