version: "3"

networks:
  pasta_net:
    external: true

services:
  pasta_chat.postgres:
    container_name: pasta_chat.postgres
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PG_PASS=pasta
      - PG_PORT=5432
    networks:
      - pasta_net
    ports:
      - "5432:5432"